# Document:
# http://simiki.org/docs/configuration.html

url: http://wiki.starscount.cn/
title: Wiki|StarsCount
keywords: wiki,starscount,simiki
description: "the Personal Wiki of StarsCount by Programs"
author: starscount
theme: yasimple

